//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNHANVIEN.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEAN()
        {
            this.PHANCONGs = new HashSet<PHANCONG>();
        }
    
        public short MADA { get; set; }
        public string TENDA { get; set; }
        public Nullable<System.DateTime> NGAYBD { get; set; }
        public Nullable<short> PHONG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHANCONG> PHANCONGs { get; set; }
        public virtual PHONGBAN PHONGBAN { get; set; }
    }
}
