//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNHANVIEN.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGBAO
    {
        public short MATB { get; set; }
        public string NOIDUNG { get; set; }
        public Nullable<System.DateTime> THOIGIAN { get; set; }
        public string VAITRO { get; set; }
        public string LINHVUC { get; set; }
        public string CHINHANH { get; set; }
        public Nullable<int> OLS_COLUMN { get; set; }
    }
}
