conn lbacsys/123;
EXECUTE SA_POLICY_ADMIN.REMOVE_TABLE_POLICY('THONGBAO_OLS_POL','AD','THONGBAO');
EXECUTE SA_POLICY_ADMIN.APPLY_TABLE_POLICY(policy_name => 'THONGBAO_OLS_POL',schema_name => 'AD',table_name  => 'THONGBAO',table_options => 'READ_CONTROL',label_function => 'AD.GET_THONGBAO_LABEL(:new.VAITRO,:new.LINHVUC,:new.CHINHANH)',predicate => NULL);

EXECUTE SA_USER_ADMIN.SET_USER_PRIVS('THONGBAO_OLS_POL','AD','FULL,PROFILE_ACCESS');


EXECUTE SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_OLS_POL','gd1','GD:MB,SX,GC:TCT');
EXECUTE SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_OLS_POL','gd43','GD:MB,SX,GC:MNam');
EXECUTE SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_OLS_POL','gd44','GD:MB,SX,GC:MBac');
EXECUTE SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_OLS_POL','tp21','TP:MB:MTrung');
EXECUTE SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_OLS_POL','nv197','NV:SX:MBac');

commit;


